dataset:
  name: "QAChave"
  reader_type: "QAChave"
  path: "datasets/qa-chave/"
  dataset_setup:
    type: "cross-validation"
    folds_splitter: "shuffle-split"
    folds: 5
    test_size: 0.4
    random_state: 0
---
dataset:
  name: "UIUC"
  reader_type: "UIUC"
  path: "datasets/UIUC/UIUC_pt"
  dataset_setup:
    type: "cross-validation"
    folds_splitter: "shuffle-split"
    folds: 5
    test_size: 0.4
    random_state: 0
#dataset:
#  name: "UIUC"
#  reader_type: "UIUC"
#  path: "datasets/UIUC/UIUC_pt"
#  dataset_setup:
#    type: "fixed-split"
#---
#dataset:
#  name: "WikiPassageQA"
#  reader_type: "WikiPassageQA"
#  path: "datasets/WikiPassageQA/"
#  dataset_setup:
#    type: "fixed-split"
#---
#dataset:
#  name: "Antique"
#  reader_type: "Antique"
#  path: "datasets/antique/"
#  dataset_setup:
#    type: "fixed-split"
#---
#dataset:
#  name: "QAChave"
#  reader_type: "QAChave"
#  path: "datasets/qa-chave/"
#  dataset_setup:
#    type: "cross-validation"
#    folds_splitter: "shuffle-split"
#    folds: 5
#    test_size: 0.4
#    random_state: 0
