import abc
from src.SettingsYAML import SettingsYAML
from src.tasks.TechniqueNLTKTokenizerWithoutStopWords import TechniqueNLTKTokenizerWithoutStopWords
from src.tasks.TechniqueRuleBased import TechniqueRuleBased
from src.tasks.TechniqueLinearSVCQuestionClassification import TechniqueLinearSVCQuestionClassification
from src.tasks.TechniqueSVMLinearQuestionClassification import TechniqueSVMLinearQuestionClassification
from src.tasks.TechniqueRetrievalBasedInformationRetrieval import TechniqueRetrievalBasedInformationRetrieval


class Task(metaclass=abc.ABCMeta):

    def __init__(self, task_id, task_name):
        self._id = task_id
        self._name = task_name
        self._technique = self._build_technique()
        self._should_evaluate = SettingsYAML.get_instance().should_evaluate(task_id)
        pass

    def build_technique(self, task_id):
        technique_name = SettingsYAML.get_instance().get_used_technique(task_id)

        if technique_name == 'nltkTokenizerWithoutStopWords':
            return TechniqueNLTKTokenizerWithoutStopWords('nltkTokenizerWithoutStopWords')
        elif technique_name == 'RuleBased':
            return TechniqueRuleBased('RuleBased')
        elif technique_name == 'LinearSVCQuestionClassification':
            return TechniqueLinearSVCQuestionClassification('LinearSVCQuestionClassification')
        elif technique_name == 'LinearSVMQuestionClassification':
            return TechniqueSVMLinearQuestionClassification('LinearSVMLinearQuestionClassification')
        elif technique_name == 'RetrievalBasedInformationRetrieval':
            return TechniqueRetrievalBasedInformationRetrieval('RetrievalBasedInformationRetrieval')
        else:
            return None

    def get_id(self):
        return self._id

    def get_name(self):
        return self._name

    def set_input_field_mapping(self, input_field_mapping):
        if self._technique:
            self._technique.set_input_field_mapping(input_field_mapping)

    def should_evaluate(self):
        return self._should_evaluate

    def _build_technique(self):
        return self.build_technique(self._id)

    def get_mapped_input_field_value(self, key):
        if self._technique:
            return self._technique.get_actual_field_name(key)
        return None

    @staticmethod
    @abc.abstractmethod
    def get_fields_for_technique():
        """
        Get the fields that are mandatory to execute the task. The source of the input fields can be the dataset or
        the result of another task.
        Field name convention:
            Dataset fields: 'dataset_*'
            Task fields: '*'
        :return: List of input fields that are mandatory for the task execution.
        """
        pass

    @abc.abstractmethod
    def run(self, resource_entries):
        """
        :return: List of results generated by the task for every resource entry that the technique were applied.
        """
        pass

    def setup(self):
        self._technique.setup()

    def train(self, train_set, dev_set, test_set, resource_articles):
        self._technique.train(train_set, dev_set, test_set, resource_articles)

    def validate(self, dev_set):
        self._technique.validate(dev_set)
