import abc
from src.tasks.TechniqueNLTKTokenizerWithoutStopWords import TechniqueNLTKTokenizerWithoutStopWords
from src.Settings import Settings


class Task(metaclass=abc.ABCMeta):

    def __init__(self, id):
        self._id = id
        self.__technique = None

    def get_id(self):
        return self._id

    def build_technique(self):
        if Settings.get_instance().get_used_technique(self._id) == 'nltkTokenizerWithoutStopWords':
            return TechniqueNLTKTokenizerWithoutStopWords('nltkTokenizerWithoutStopWords')
        else:
            return None

    @staticmethod
    @abc.abstractmethod
    def get_fields_for_technique():
        """
        Get the fields that are mandatory to execute the task. The source of the input fields can be the dataset or
        the result of another task.
        Field name convention:
            Dataset fields: 'dataset_*'
            Task fields: '*'
        :return: List of input fields that are mandatory for the task execution.
        """
        pass

    @abc.abstractmethod
    def run(self, resource_entries):
        """
        :return: List of results generated by the task for every resource entry that the technique were applied.
        """
        pass

    def train(self, train_set):
        pass

    def validate(self, dev_set):
        pass
